name: altogic
description: Dart client for Altogic. Altogic is a backend application development and execution platform, enabling people and businesses to design, deploy and manage scalable applications.
homepage: https://github.com/altogic/altogic-flutter
repository: https://github.com/altogic/altogic-flutter
version: 0.0.9
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  altogic_dart: ^0.0.9
  app_links: ^3.3.0

  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6



dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter



flutter: